spring.application.name=BootMVC_P03-DataRendering-2WebPageApplication

#view resolver config
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

#embedded server port
server.port=4041

#context of embedded server
server.servlet.context-path=/DataRenderingApp